import '../../app/globals.css';
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
const NotoSans = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zero Build",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
   <html lang="en" className="darks" suppressHydrationWarning>
      <body className={NotoSans.className} suppressHydrationWarning>
        <div className="relative w-full flex items-center justify-center">
          <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
